# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bafa8d902ad2764a0c28cc7bba8912d7c93ca5e0b1a609c21c4e5803eb1fd5b87999cb4ade884d5c33bcf0b80d5aca57867f217bd3bdff8ad853e3c6722f8adb

test:
  secret_key_base: 00e36e538bb1af38c4c31b2eb2d58c96190df577e18e6a8c87427e815c4dafbcb724816b700b7321e3c73964c1f1b9e438aa8aff0ade4891a417ebd626f74497

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
